import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://auth-uat.doxa-holdings.com/login');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('developer_admin@getnada.com');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('12345678');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('https://subcon-uat.doxa-holdings.com/dashboard');
  await page.getByText('Requisitions').click();
  await page.locator('a').filter({ hasText: 'Requisitions' }).click();
  await page.getByRole('link', { name: 'Raise Requisition' }).click();
  await page.getByRole('button', { name: ' Add Manual' }).click();
  await page.getByRole('gridcell').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('textbox', { name: 'Input Editor' }).fill('work 1');
  await page.getByRole('gridcell').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('textbox', { name: 'Input Editor' }).fill('auto');
  await page.getByRole('gridcell').filter({ hasText: /^$/ }).nth(5).click();
  await page.getByText('PCS').click();
  await page.locator('.ag-row.ag-row-odd > .ag-cell.ag-cell-not-inline-editing.ag-cell-auto-height.ag-cell-value.ag-column-hover').click();
  await page.getByRole('textbox', { name: 'Input Editor' }).fill('1');
  await page.locator('.ag-row.ag-row-odd > .ag-cell.ag-cell-not-inline-editing.ag-cell-auto-height.ag-cell-value.ag-column-hover').click();
  await page.getByRole('textbox', { name: 'Input Editor' }).fill('1000');
  await page.getByRole('textbox', { name: 'Input Editor' }).press('Enter');
  await page.locator('svg').first().click();
  await page.locator('#react-select-2-input').fill('dtf-auto');
  await page.getByText('DTF-AUTO-011-PO (DTF-AUTO-011)', { exact: true }).click();
  await page.getByRole('button', { name: 'Please Select Project Trade' }).click();
  await page.getByText('BW (Building Work)').click();
  await page.getByRole('textbox', { name: 'Enter Contract Title' }).click();
  await page.getByRole('textbox', { name: 'Enter Contract Title' }).fill('WR-Auto');
  await page.locator('select[name="contractType"]').selectOption('LUMP_SUM');
  await page.locator('.mb-0 > .col-md-8 > .css-2b097c-container > .css-aizk4s-control > .css-1wy0on6 > .css-kaayk1-indicatorContainer').click();
  await page.locator('div').filter({ hasText: /^Please select Person-in-Charge \(Respondent\)$/ }).nth(3).click();
  await page.locator('#react-select-3-option-1').click();
  await page.getByRole('textbox', { name: '10%' }).click();
  await page.getByRole('textbox', { name: '10%' }).fill('0');
  await page.getByPlaceholder('5%').click();
  await page.getByPlaceholder('5%').fill('0');
  await page.locator('svg').nth(2).click();
  await page.getByText('MAINCON01 (MAINCON PTE LTD)', { exact: true }).click();
  await page.getByRole('button', { name: 'Submit for Approval' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
});