import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  // await page.goto('https://auth-uat.doxa-holdings.com/login');
  // await page.getByRole('textbox', { name: 'Email *' }).click();
  // await page.getByRole('textbox', { name: 'Email *' }).fill('developer_admin@getnada.com');
  // await page.getByRole('textbox', { name: 'Password *' }).click();
  // await page.getByRole('textbox', { name: 'Password *' }).fill('12345678');
  // await page.getByRole('button', { name: 'Login' }).click();
  // await page.goto('https://subcon-uat.doxa-holdings.com/dashboard');
  // await page.getByText('Requisitions').click();
  // await page.locator('a').filter({ hasText: 'Requisitions' }).click();
  // await page.getByRole('link', { name: 'Raise Requisition' }).click();
  await page.getByRole('button', { name: ' Upload.csv' }).click();
  await page.getByRole('button', { name: ' Upload.csv' }).setInputFiles('Project Owner - Maincon 1 2.csv');
  await page.getByText('Please select Project', { exact: true }).click();
  await page.getByText('PRJ-AUTO-001 (DTF-AUTO-001)', { exact: true }).click();
  await page.getByRole('button', { name: 'Please Select Project Trade' }).click();
  await page.getByText('BW (Building Work)').click();
  await page.getByRole('textbox', { name: 'Enter Contract Title' }).click();
  await page.getByRole('textbox', { name: 'Enter Contract Title' }).fill('WR-Auto-001');
  await page.locator('select[name="contractType"]').selectOption('LUMP_SUM');
  await page.getByText('Please select Person-in-').click();
  await page.locator('#react-select-3-option-1').click();
  await page.getByRole('textbox', { name: '10%' }).click();
  await page.getByRole('textbox', { name: '10%' }).fill('0');
  await page.getByPlaceholder('5%').click();
  await page.getByPlaceholder('5%').fill('0');
  await page.getByText('Please Select Vendor Code').click();
  await page.getByText('MAINCON01 (MAINCON PTE LTD)', { exact: true }).click();
  await page.getByRole('button', { name: 'Submit for Approval' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'I Understand' }).click();
});